### ISSUE TITLE
[todo] new user sign up experience

### ISSUE THREAD

**Issue by jalaj711** [jalaj711/finance-tracker#3]
With the sign-in introduced in commit 3172565179d9947d7c84af054a7fbd0c6e7e4a98, the following tasks are at hand to make the experience seamless:

- [x] Create a new default wallet
- [x] Show "No data" in recent transactions and on graphs in the dashboard
- [x] The Add transaction page crashes because of `labels` field being undefined in `store.auth.user_data`. This is the line causing this problem: https://github.com/jalaj711/finance-tracker/blob/3172565179d9947d7c84af054a7fbd0c6e7e4a98/pages/add.tsx#L173. However, I believe this is something to be fixed at the backend.
