### ISSUE TITLE
[todo] Redesign the bottom navigation bar

### ISSUE THREAD

**Issue by jalaj711** [jalaj711/finance-tracker#4]
Currently, there are some  issues with the bottom navigation bar that need to be addressed:

- [x] It doesn't have a link for the labels page. This makes it difficult for users to access the labels page.
- [x] Make space for a user profile page where the user should be able to edit his/her account info and log out from the system
- [ ] The current layout limits the number of links that can be put there because of width limitations on smartphones. Thus, this layout needs to be changed. We can probably use a speed dial kind of thing.

**Comment by jalaj711** [comment]
Much of the issues posed were fixed in https://github.com/jalaj711/finance-tracker/commit/14eb8dc52504ddfe03a4360af049424d7760c378. Now, all the required links are placed in the current design itself.
